services:

  # =================================================================
  # ðŸšª API GATEWAY (Ãšnico Punto de Acceso PÃºblico)
  # =================================================================
  gateway:
    build: ./gateway
    container_name: api_gateway
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8000" # Acceso a Docs del Gateway
    depends_on:
      - users-service
      - incidents-service
    networks:
      - public-network
      - internal-network
      
  # -----------------------------------------------------------------
  # ðŸ‘¤ ECOSYSTEM: USERS
  # -----------------------------------------------------------------
  
  users-db:
    image: postgres:15-alpine
    container_name: users_db_container
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${USERS_DB_USER}
      POSTGRES_PASSWORD: ${USERS_DB_PASSWORD}
      POSTGRES_DB: ${USERS_DB_NAME}
    volumes:
      - users_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${USERS_DB_USER} -d ${USERS_DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - internal-network

  users-service:
    build: ./users-service
    container_name: users_service_container
    restart: always
    env_file:
      - .env
    depends_on:
      users-db:
        condition: service_healthy
    environment:
      DB_USER: ${USERS_DB_USER}
      DB_PASSWORD: ${USERS_DB_PASSWORD}
      DB_NAME: ${USERS_DB_NAME}
      DB_HOST: users-db
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    #ports:
      #- "8001:8000" # <--- Expuesto para ver Swagger en localhost:8001/docs (ELIMINADO PARA SEGURIDAD)

    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - internal-network
  
  # -----------------------------------------------------------------
  # âš ï¸ ECOSYSTEM: INCIDENTS
  # -----------------------------------------------------------------

  incidents-db:
    image: postgres:15-alpine
    container_name: incidents_db_container
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${INCIDENTS_DB_USER}
      POSTGRES_PASSWORD: ${INCIDENTS_DB_PASSWORD}
      POSTGRES_DB: ${INCIDENTS_DB_NAME}
    volumes:
      - incidents_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${INCIDENTS_DB_USER} -d ${INCIDENTS_DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - internal-network

  incidents-service:
    build: ./incidents-service
    container_name: incidents_service_container
    restart: always
    env_file:
      - .env
    depends_on:
      incidents-db:
        condition: service_healthy
      users-service:
        condition: service_started
    environment:
      DB_USER: ${INCIDENTS_DB_USER}
      DB_PASSWORD: ${INCIDENTS_DB_PASSWORD}
      DB_NAME: ${INCIDENTS_DB_NAME}
      DB_HOST: incidents-db
      DB_PORT: 5432
      USERS_SERVICE_URL: ${USERS_SERVICE_URL}
      #VARIABLES JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
    #ports:
      #- "8002:8000" # <--- Expuesto para ver Swagger en localhost:8002/docs (ELIMINADO PARA SEGURIDAD)

    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - internal-network

  # -----------------------------------------------------------------
  # ðŸ–¥ï¸ FRONTEND
  # -----------------------------------------------------------------
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    env_file:
      - .env
    ports:
      - "5173:80"
    depends_on:
      - gateway
    networks:
      - public-network
      - internal-network


volumes:
  users_data: {}
  incidents_data: {}

networks:
  internal-network:     # Red privada (BBDD y Backends)
    internal: true      # Impide acceso desde fuera (opcional)
  public-network:       # Red pÃºblica (Gateway y Frontend)
    driver: bridge